name: zeronet
description: "Emergency response app for hospitality and field staff."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  intl: ^0.20.2
  provider: any
  sensors_plus: any
  geolocator: any
  geocoding: any
  battery_plus: any
  connectivity_plus: any
  flutter_blue_plus: any
  flutter_ble_peripheral: any
  flutter_background_service: any
  location: any
  permission_handler: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
